name: Updater (WIP)

on:
  schedule:
    - cron: '0 0 * * 0'  # Scheduled to run weekly at midnight on Sunday
  workflow_dispatch:     # Allows manual trigger from GitHub

permissions:
  contents: write

jobs:
  update:
    if: github.repository_owner == 'wowchemy'
    runs-on: ubuntu-latest
    steps:
      - uses: wowchemy/gh-action-updater@v1
        with:
          feed-url: https://wowchemy.com/blog/index.xml
          readme-section: news
          branch: main
